# select your canteen key for your preferred canteen. A list of keys can be found here: https://github.com/TUM-Dev/eat-api
CANTEEN_KEY = "mensa-garching"


# go to https://www.mvv-muenchen.de/fahrplanauskunft/fuer-entwickler/homepage-services/index.html and configure your preferred monitor 
FIRST_MONITOR_LABEL = "Richtung Grosshadern"
SECOND_MONITOR_LABEL = "Richtung Garching"


# copy and paste the complete <div></div> element into the string
FIRST_MONITOR_CODE = '<div class="mvv-departure-monitor" monitor-configuration="eyJsYW5ndWFnZSI6eyJkZXBhcnR1cmUiOiJBYmZhaHJ0IiwidHJhaW5TdG9wcyI6IkhhbHRlc3RlbGxlbiIsImRpcmVjdGlvbiI6IlJpY2h0dW5nIiwiZm9vdGVyTm90ZSI6IqkgQ29weXJpZ2h0IiwiZm9vdGVyVGV4dCI6IldlaXRlcmUgRmFocnBsYW5hdXNr/G5mdGUgdW50ZXIgd3d3Lm12di1hdXNrdW5mdC5kZSBvZGVyIG1pdCBkZXIgTVZWLUFwcCIsImhlYWRlclRleHQiOiJBYmZhaHJ0ZW4gZvxyIGhldXRlLCAiLCJsYW5ndWFnZSI6ImRlIiwibGluZSI6IkxpbmllIiwibGl2ZSI6IkxpdmUiLCJzdG9wIjoiSGFsdGVzdGVsbGUiLCJ0cmFjayI6IkdsZWlzIn0sImlzRnVsbHNjcmVlbiI6ZmFsc2UsInN0YXRpb25zIjpbeyJzdGF0aW9uIjp7InVzYWdlIjoic2YiLCJ0eXBlIjoiYW55IiwibmFtZSI6Ik38bmNoZW4sIFN0dWRlbnRlbnN0YWR0Iiwic3RhdGVsZXNzIjoiOTEwMDA1NDAiLCJhbnlUeXBlIjoic3RvcCIsInNvcnQiOiIyIiwicXVhbGl0eSI6IjYyMiIsImJlc3QiOiIxIiwib2JqZWN0IjoiU3R1ZGVudGVuc3RhZHQiLCJtYWluTG9jIjoiTfxuY2hlbiIsIm1vZGVzIjoiMiw1LDYsNyIsInJlZiI6eyJpZCI6IjkxMDAwNTQwIiwiZ2lkIjoiZGU6MDkxNjI6NTQwIiwib21jIjoiOTE2MjAwMCIsInBsYWNlSUQiOiIxIiwicGxhY2UiOiJN/G5jaGVuIiwiY29vcmRzIjoiMTI5MjE4NS4wMDAwMCw1ODYyNTM0LjAwMDAwIn0sImlkIjoiZGU6MDkxNjI6NTQwIn0sImxpbmVzIjpbeyJudW1iZXIiOiJVNiIsInN5bWJvbCI6IjAxMFU2LnN2ZyIsImRpcmVjdGlvbiI6IktsaW5pa3VtIEdyb99oYWRlcm4iLCJzdGF0ZWxlc3MiOiJzd206MDEwVTY6RzpIOjAxNCIsIm5hbWUiOiJVLUJhaG4ifV0sImxlYWRUaW1lTWludXRlcyI6M31dLCJsaW5lcyI6W10sIm1heFJlc3VsdHMiOjQsImZldGNoSW50ZXJ2YWxJbk1pbnV0ZXMiOjMsInNob3dOb3RpZmljYXRpb24iOnRydWV9"></div>'
SECOND_MONITOR_CODE = '<div class="mvv-departure-monitor" monitor-configuration="eyJsYW5ndWFnZSI6eyJkZXBhcnR1cmUiOiJBYmZhaHJ0IiwidHJhaW5TdG9wcyI6IkhhbHRlc3RlbGxlbiIsImRpcmVjdGlvbiI6IlJpY2h0dW5nIiwiZm9vdGVyTm90ZSI6IqkgQ29weXJpZ2h0IiwiZm9vdGVyVGV4dCI6IldlaXRlcmUgRmFocnBsYW5hdXNr/G5mdGUgdW50ZXIgd3d3Lm12di1hdXNrdW5mdC5kZSBvZGVyIG1pdCBkZXIgTVZWLUFwcCIsImhlYWRlclRleHQiOiJBYmZhaHJ0ZW4gZvxyIGhldXRlLCAiLCJsYW5ndWFnZSI6ImRlIiwibGluZSI6IkxpbmllIiwibGl2ZSI6IkxpdmUiLCJzdG9wIjoiSGFsdGVzdGVsbGUiLCJ0cmFjayI6IkdsZWlzIn0sImlzRnVsbHNjcmVlbiI6ZmFsc2UsInN0YXRpb25zIjpbeyJzdGF0aW9uIjp7InVzYWdlIjoic2YiLCJ0eXBlIjoiYW55IiwibmFtZSI6Ik38bmNoZW4sIFN0dWRlbnRlbnN0YWR0Iiwic3RhdGVsZXNzIjoiOTEwMDA1NDAiLCJhbnlUeXBlIjoic3RvcCIsInNvcnQiOiIyIiwicXVhbGl0eSI6IjYyMiIsImJlc3QiOiIxIiwib2JqZWN0IjoiU3R1ZGVudGVuc3RhZHQiLCJtYWluTG9jIjoiTfxuY2hlbiIsIm1vZGVzIjoiMiw1LDYsNyIsInJlZiI6eyJpZCI6IjkxMDAwNTQwIiwiZ2lkIjoiZGU6MDkxNjI6NTQwIiwib21jIjoiOTE2MjAwMCIsInBsYWNlSUQiOiIxIiwicGxhY2UiOiJN/G5jaGVuIiwiY29vcmRzIjoiMTI5MjE4NS4wMDAwMCw1ODYyNTM0LjAwMDAwIn0sImlkIjoiZGU6MDkxNjI6NTQwIn0sImxpbmVzIjpbeyJudW1iZXIiOiJVNiIsInN5bWJvbCI6IjAxMFU2LnN2ZyIsImRpcmVjdGlvbiI6IkZy9nR0bWFuaW5nIiwic3RhdGVsZXNzIjoic3dtOjAxMFU2Okc6UjowMTQiLCJuYW1lIjoiVS1CYWhuIn1dLCJsZWFkVGltZU1pbnV0ZXMiOjN9XSwibGluZXMiOltdLCJtYXhSZXN1bHRzIjo0LCJmZXRjaEludGVydmFsSW5NaW51dGVzIjozLCJzaG93Tm90aWZpY2F0aW9uIjp0cnVlfQ=="></div>'


# MVG API configuration (for mvg package)
# Provide station names as displayed by MVG, e.g. "Universität, München"
# Optionally restrict to transport types: UBAHN, SBAHN, TRAM, BUS
FIRST_MONITOR_STATION = "Studentenstadt, München"  # TODO: set your preferred station
MVG_FIRST_TRANSPORT_TYPES = ["UBAHN"]
MVG_SECOND_TRANSPORT_TYPES = ["UBAHN"]
MVG_DEPARTURE_LIMIT = 4

# Walking-time offset in minutes to the station
MVG_FIRST_OFFSET_MINUTES = 5

